# Generated by Django 5.0 on 2023-12-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название сети')),
                ('url', models.CharField(max_length=128, verbose_name='Ссылка на сеть')),
                ('image', models.ImageField(upload_to='contacts', verbose_name='Логотип сети')),
            ],
        ),
        migrations.CreateModel(
            name='Objacts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128, verbose_name='Название предмета')),
                ('description', models.TextField(default=None, null=True, verbose_name='Описание предмета')),
                ('image', models.ImageField(default=None, upload_to='objacts_img', verbose_name='Изображение предмета')),
            ],
        ),
    ]
