# Generated by Django 5.0 on 2023-12-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='objacts',
            name='lang',
            field=models.CharField(blank=True, choices=[('en', 'Английский'), ('ru', 'Русский'), ('ud', 'Удмуртский')], default='ru', max_length=2, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='objacts',
            name='description',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Описание предмета'),
        ),
        migrations.AlterField(
            model_name='objacts',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='objacts_img', verbose_name='Изображение предмета'),
        ),
    ]
