# Generated by Django 5.0 on 2023-12-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_objacts_lang_alter_objacts_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': 'контакта', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AlterModelOptions(
            name='objacts',
            options={'verbose_name': 'предмета', 'verbose_name_plural': 'Предметы'},
        ),
        migrations.RemoveField(
            model_name='objacts',
            name='description',
        ),
        migrations.RemoveField(
            model_name='objacts',
            name='lang',
        ),
        migrations.RemoveField(
            model_name='objacts',
            name='title',
        ),
        migrations.AddField(
            model_name='objacts',
            name='en_description',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Описание предмета (en)'),
        ),
        migrations.AddField(
            model_name='objacts',
            name='en_title',
            field=models.CharField(default=0, max_length=128, verbose_name='Название предмета (en)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='objacts',
            name='ru_description',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Описание предмета (ру)'),
        ),
        migrations.AddField(
            model_name='objacts',
            name='ru_title',
            field=models.CharField(default=0, max_length=128, verbose_name='Название предмета (ру)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='objacts',
            name='ud_description',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Описание предмета (удм)'),
        ),
        migrations.AddField(
            model_name='objacts',
            name='ud_title',
            field=models.CharField(default=0, max_length=128, verbose_name='Название предмета (удм)'),
            preserve_default=False,
        ),
    ]
