# Generated by Django 5.0 on 2023-12-27 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0004_datafromindexpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datafromindexpage',
            options={'verbose_name': 'информации', 'verbose_name_plural': 'Информация на главной странице'},
        ),
    ]
