# Generated by Django 5.0.2 on 2024-05-10 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('url', models.CharField(max_length=255, verbose_name='Ссылка')),
                ('img', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='DataFromIndexPage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[], max_length=5, verbose_name='Место где отображать')),
                ('ru_text', models.TextField(blank=True, null=True, verbose_name='Текст на русском')),
                ('ud_text', models.TextField(blank=True, null=True, verbose_name='Текст на удмуртском')),
                ('en_text', models.TextField(blank=True, null=True, verbose_name='Текст на английском')),
            ],
            options={
                'verbose_name': 'Данные из главной страницы',
                'verbose_name_plural': 'Данные из главной страницы',
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ru_description', models.TextField(blank=True, null=True, verbose_name='Описание на русском')),
                ('ru_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название на русском')),
                ('ud_description', models.TextField(blank=True, null=True, verbose_name='Описание на удмуртском')),
                ('ud_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название на удмуртском')),
                ('en_description', models.TextField(blank=True, null=True, verbose_name='Описание на английском')),
                ('en_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название на английском')),
                ('img', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
    ]
