# Generated by Django 5.0 on 2024-02-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='DataFromIndexPage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[], max_length=5)),
                ('ru_text', models.TextField()),
                ('ud_text', models.TextField()),
                ('en_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ru_title', models.CharField(max_length=255)),
                ('ru_description', models.TextField()),
                ('ud_title', models.CharField(max_length=255)),
                ('ud_description', models.TextField()),
                ('en_title', models.CharField(max_length=255)),
                ('en_description', models.TextField()),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
    ]
