# Generated by Django 5.0 on 2024-02-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AlterModelOptions(
            name='datafromindexpage',
            options={'verbose_name': 'Данные из главной страницы', 'verbose_name_plural': 'Данные из главной страницы'},
        ),
        migrations.AlterModelOptions(
            name='items',
            options={'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
        migrations.AddField(
            model_name='contacts',
            name='img_svg',
            field=models.TextField(blank=True, null=True, verbose_name='SVG Изображение'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='url',
            field=models.CharField(max_length=255, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='datafromindexpage',
            name='en_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст на английском'),
        ),
        migrations.AlterField(
            model_name='datafromindexpage',
            name='ru_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст на русском'),
        ),
        migrations.AlterField(
            model_name='datafromindexpage',
            name='type',
            field=models.CharField(choices=[], max_length=5, verbose_name='Место где отображать'),
        ),
        migrations.AlterField(
            model_name='datafromindexpage',
            name='ud_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст на удмуртском'),
        ),
        migrations.AlterField(
            model_name='items',
            name='en_description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание на английском'),
        ),
        migrations.AlterField(
            model_name='items',
            name='en_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название на английском'),
        ),
        migrations.AlterField(
            model_name='items',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='items',
            name='ru_description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание на русском'),
        ),
        migrations.AlterField(
            model_name='items',
            name='ru_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название на русском'),
        ),
        migrations.AlterField(
            model_name='items',
            name='ud_description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание на удмуртском'),
        ),
        migrations.AlterField(
            model_name='items',
            name='ud_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название на удмуртском'),
        ),
    ]
