# Generated by Django 5.0 on 2024-02-05 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_contacts_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='img_svg',
        ),
    ]
